namespace AdventOfCode2024.Tests;

public class Day06Tests
{
    [Fact]
    public void SimulateGuardMovementIsCorrect()
    {
        const string input = """
                             ....#.....
                             .........#
                             ..........
                             ..#.......
                             .......#..
                             ..........
                             .#..^.....
                             ........#.
                             #.........
                             ......#...
                             """;
        var result = Day06.DistinctPositions(input);
        Assert.Equal(41, result);
    }
    
    [Fact]
    public void CalculatePossibleGuardLoopPositionsIsCorrect()
    {
        const string input = """
                             ....#.....
                             .........#
                             ..........
                             ..#.......
                             .......#..
                             ..........
                             .#..^.....
                             ........#.
                             #.........
                             ......#...
                             """;
        var result = Day06.CalculatePossibleGuardLoopPositions(input);
        Assert.Equal(6, result);
    }
}